version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: graphql-debug_app
    networks:
      - external
      - internal
    volumes:
      - ./backend:/backend

  http-proxy:
    image: nginx:1.21.5-alpine
    container_name: graphql-debug_http-proxy
    depends_on:
      - app
    networks:
      - external
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./docker/http-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/frontend

networks:
  internal:
  external:
